# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ajax_select_boxes_dev_db
  pool: 5
  username: root
  password: helmut407
  host: localhost

